<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	  <LangVersion>latest</LangVersion>
	  <Nullable>enable</Nullable>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <Title>JustSomeLogging</Title>
	  <Authors>BigTylis</Authors>
	  <Description>Simple, performant, extensible, and easy to use logging library for C#</Description>
	  <Copyright>Copyright (c) 2026, BigTylis</Copyright>
	  <RepositoryType>git</RepositoryType>
	  <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
	  <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
	  <RepositoryUrl>https://github.com/BigTylis/JustSomeLogging</RepositoryUrl>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <PackageIcon>icon-v2.png</PackageIcon>
	  <PackageTags>log;logging;netstandard2.0;windows;linux;mac;</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="JustSomeLogging.Run\**" />
    <EmbeddedResource Remove="JustSomeLogging.Run\**" />
    <None Remove="JustSomeLogging.Run\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\icon-v2.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
	  <None Include="..\LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild" Version="5.12.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    <PackageReference Include="PolySharp" Version="1.16.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Threading.Channels" Version="10.0.11" />
  </ItemGroup>

</Project>
