name: GitVersion Autotag

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'

jobs:
  tag-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: '5.12.0'

      - name: Calculate Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3
        with:
          useConfigFile: true

      - name: Create Tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          TAG_NAME="v${{ steps.gitversion.outputs.semVer }}"

          echo "Generating and pushing tag: $TAG_NAME"
          git tag $TAG_NAME
          git push origin $TAG_NAME
